### ISSUE TITLE
Run instructions

### ISSUE THREAD

**Issue by Wulfheart** [hauketoenjes/messdienerplan_api#2]
Bin leider nicht so gut mit Docker, normalerweise funktionieren meine Container wundersamerweise. 😅

Ich habe `docker-compose up` ausgeführt, aber da kriege ich ein Problem mit nicht gesetzten Variablen für die Datenbank. Wo muss ich da noch was setzen und unter welcher Adresse erreiche ich die API? Gibt es irgendwo eine Übersicht über die Definitionen?

Danke im Voraus.

**Comment by hauketoenjes** [comment]
Hi, 

Ich hab gerade eine Anleitung zum Starten der API in die [Readme](https://github.com/hauketoenjes/messdienerplan_api#installation) geschrieben. Damit solltest du das Projekt gestartet bekommen. 

##### Allgemein zur Dokumentation:

Ich werde demnächst eine API Dokumentation mit weiteren Informationen hinzufügen, damit auch Andere das Projekt verwenden können. 

Bis dahin kannst du am besten mit der Django Oberfläche arbeiten, mit der man sich auch relativ gut durch die API klicken kann. Wenn das Projekt läuft, findet man sie auf `/api/v1/`.

**Comment by Wulfheart** [comment]
Danke.
Gibt es irgendwelche Dummy-Werte, die ich einfügen kann? Weil das läuft dann eh nur in meinem lokalen Docker-Container.
```
SECRET_KEY=
MYSQL_ROOT_PASSWORD=
DATABASE_NAME=
DATABASE_USER=
DATABASE_PASSWORD=
DATABASE_HOST=
DATABASE_PORT=
DJANGO_SUPERUSER_USERNAME=
DJANGO_SUPERUSER_PASSWORD=
DJANGO_SUPERUSER_EMAIL=
MAPI_KAPLAN_URL=
```

**Comment by hauketoenjes** [comment]
Ja klar, du kannst da eintragen, was du möchtest. 

Im Grunde sind die Variablen alle in der [sample.env](https://github.com/hauketoenjes/messdienerplan_api/blob/main/sample.env) erklärt. Das einzige was noch anzumerken ist, ist das der Datenbank host `database` ist, wenn man die docker-compose verwendet (standardmäßig dann Port `3306`). 

Hier mal eine Beispiel `.env` Datei:

```
SECRET_KEY=123
DJANGO_SUPERUSER_USERNAME=admin
DJANGO_SUPERUSER_PASSWORD=admin123
DJANGO_SUPERUSER_EMAIL=admin@example.com
MAPI_KAPLAN_URL=
MYSQL_ROOT_PASSWORD=root
DATABASE_NAME=django
DATABASE_USER=django
DATABASE_PASSWORD=django
DATABASE_HOST=database
DATABASE_PORT=3306
```

**Comment by Wulfheart** [comment]
Danke! 
Wenn ich aber dann `http://localhost:8080/admin` besuche und `admin` und `admin123` angebe, dann bekomme ich einen `500`er Fehler. 

> Die Datenbank braucht eine gewisse Zeit beim ersten Start des Stacks. Es kann passieren, dass Django dann einen Verbindungsabbruch bekommt und die Datenbank nicht initialisieren kann. Um das zu verhindern, sollte die Datenbank vor Django gestartet werden. Das Problem tritt meistens nur beim allerersten Start des Stacks auf. Danach kann man das ganze Projekt gemeinsam starten.

Wie mache ich das am blödsten? Funktioniert das dann?

**Comment by hauketoenjes** [comment]
Ja genau, das passiert, weil Django beim Start die Datenbank nicht anlegen kann. Am einfachsten kann man dann Django einmal mit `docker-compose restart mapi` neustarten. Dann sollte die Datenbank angelegt werden und du solltest dich einloggen können.

**Comment by Wulfheart** [comment]
Ah, super. Jetzt klappt es! Ich werde mal ein wenig damit rumexperimentieren.
